"""update field 

Revision ID: 65d9f8b15e5b
Revises: 9d5ff1d90ecd
Create Date: 2024-03-28 13:20:11.276739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d9f8b15e5b'
down_revision = '9d5ff1d90ecd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
