"""update table image product 

Revision ID: 6c6c23c3dee0
Revises: 8ae706a697af
Create Date: 2024-04-12 21:52:13.307858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c6c23c3dee0'
down_revision = '8ae706a697af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_image', sa.Column('main_image', sa.Boolean(), nullable=False))
    op.drop_column('products_image', 'main_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_image', sa.Column('main_img', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('products_image', 'main_image')
    # ### end Alembic commands ###
