"""update database

Revision ID: 8ae706a697af
Revises: 02c98857f416
Create Date: 2024-03-29 14:21:56.564221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae706a697af'
down_revision = '02c98857f416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colors', sa.Column('color_code', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('user_code', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_code')
    op.drop_column('colors', 'color_code')
    # ### end Alembic commands ###
