"""update type 

Revision ID: 8e83f1334e81
Revises: 6f80720436d2
Create Date: 2024-03-26 17:18:24.301163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e83f1334e81'
down_revision = '6f80720436d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category',
               existing_type=sa.String(length=500),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
