"""update field 

Revision ID: fe495ada7e7c
Revises: 65d9f8b15e5b
Create Date: 2024-03-28 13:31:53.074358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe495ada7e7c'
down_revision = '65d9f8b15e5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
