"""add product color 

Revision ID: fee9ce148de5
Revises: f86c617de169
Create Date: 2024-03-28 11:49:02.824246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee9ce148de5'
down_revision = 'f86c617de169'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_color',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('color_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_color_color_id'), 'product_color', ['color_id'], unique=False)
    op.create_index(op.f('ix_product_color_id'), 'product_color', ['id'], unique=False)
    op.create_index(op.f('ix_product_color_product_id'), 'product_color', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_color_product_id'), table_name='product_color')
    op.drop_index(op.f('ix_product_color_id'), table_name='product_color')
    op.drop_index(op.f('ix_product_color_color_id'), table_name='product_color')
    op.drop_table('product_color')
    # ### end Alembic commands ###
